version: '3.8'

services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rails s -p 3000 -b '0.0.0.0' -p 3010"
    volumes:
      - .:/app
    ports:
      - "3010:3010"
    depends_on:
      - db
      - elasticsearch
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200
      DATABASE_URL: postgres://postgres:password@db:5432/cgtrader_development

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cgtrader_development
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  postgres:
  elasticsearch:
